version: '3.5'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9020:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    user: root
    depends_on:
      - prometheus
    ports:
      - "3020:3000"
    volumes:
      - ./grafana:/var/lib/grafana/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    restart: unless-stopped